### ISSUE TITLE
"Tumult" repository & solution name suggests it comes from us, though it doesn't

### ISSUE THREAD

**Issue by TedTed** [usnistgov/privacy_collaborative_reserach_cycle#57]
Hi folks,

Someone looking through the different folders in [this part of the repo](https://github.com/usnistgov/privacy_collaborative_research_cycle/tree/research-acceleration-bundle/crc_metareport_bundle_1.2) might get the incorrect impression that the "tumult" solution is affiliated with us (Tumult Labs), given how other folder names actually match the affiliations of teams participating to the CRC (MostlyAI, Sarus, Anonos, etc.). We're very glad you found our software (Tumult Analytics) helpful to generate a simple DP histogram, but we'd like to avoid giving people a false impression that this was done by us or that this was an actual attempt at getting good utility. Could this folder be renamed to "simple-dp-histogram" or something similar?

As an aside, in [this file](https://github.com/usnistgov/privacy_collaborative_research_cycle/blob/research-acceleration-bundle/crc_data_and_metric_bundle_1.2/index.csv), the library name should be "Tumult Analytics", not "tumult".

Thanks a ton in advance!

**Comment by garyhowarth** [comment]
Hi Ted, 

I appreciate your feedback. Your concerns make sense. 

We have several libraries where we (CRC organizers) ran publicly available algorithms. So, the structure we're using is `library_algorithm` rather than `submission-team_algorithm`. In the metadata JSON, we list the specific team who generated the data. In the Tumult case, it lists "CRC".   

First, I'm happy to fix the library name from "tumult" to "Tumult Analytics" throughout our resources. Regarding the repo directories name, I propose to add documentation in the readme clarifying how to identify the team that generated the data. On our ['summary table'](https://pages.nist.gov/privacy_collaborative_research_cycle/pages/archive.html) we make try to make it clear that the CRC organizers ran the synthesizer when that is the case.

Let me know if those changes satisfy your concerns. Thank you very much for reaching out.

**Comment by TedTed** [comment]
Heya! This makes sense. Maybe in the summary table, putting the algorithm name as the first column (which is where people will tend to look for a "header" describing what's in this column) would also be helpful.
